# This compose file is used to test two existing docker builds against cisterne.
# It is not parameterised, you must change it to accomodate the test situation you are in.
# The main purpose is to test a "golden" version against a "tested" version, e.g. if you
# suspect a non-intended change in behaviour.

# golden: The container assumed to work correctly
# tested: The container assumed to potentially work incorrectly

# Use an extension (v3.4) to set up common configuration
x-info:
  environment: &common-env
    - AAA_IP_LIST=0.0.0.0-255.255.255.255
    # - AAA_FORS_RIGHTS=http://forsrights.addi.dk/1.2-opensearch/?action=forsRights&outputType=php&userIdAut=%s&groupIdAut=%s&passwordAut=%s&ipAddress=%s
    - AAA_FORS_RIGHTS=
    - AGENCY_END_POINT=http://openagency.addi.dk/2.34/
    - AGENCY_FALLBACK=100200
    - AGENCY_PROFILE_FALLBACK=test
    - FEDORA=http://corepo-content-service-replica.cisterne.svc.cloud.dbc.dk/rest/
    - HOLDINGS_DB=http://holdings-service.cisterne.svc.cloud.dbc.dk/getAllAvailability?pid=%s
    - HOLDINGS_ITEMS_INDEX=cisterne-corepo-searcher
    - RAW_RECORD_CONTENT_SERVICE=http://rawrepo-content-service.cisterne.svc.cloud.dbc.dk/RawRepoContentService
    - RAW_RECORD_REPOSITORY_NAME=prod-rawrecords
    - RAW_RECORD_SOLR=http://cisterne-solr.dbc.dk:8985/solr/cisterne-rawrepo-searcher/select
    - REPOSITORY_NAME=prod
    - SERVICE_LOCATION=
    - MY_DOMAIN_IP_LIST=172.16.0.0-172.20.255.255;192.168.0.0-192.168.255.255
    - SOLR=http://cisterne-solr.dbc.dk:8986/solr/cisterne-corepo-searcher/select
    - VERBOSE_LEVEL=WARNING+ERROR+FATAL+STAT+TIMER+TRACE+DEBUG
    - OPEN_FORMAT=http://openformat-php-master.frontend-prod.svc.cloud.dbc.dk/server.php
    - OLD_OPEN_FORMAT=http://openformat.addi.dk/0.2/
    - URL_PATH=
    - USE_HOLDING_BLOCK_JOIN=yes
  anchors:
    - &GOLDEN docker-os.dbc.dk/opensearch-webservice-5.2:268
    - &TESTED docker-os.dbc.dk/opensearch-webservice-5.2:305

version: '3.4'

services:

  # The images under test - both using internal memcaches
  golden:
    image: *GOLDEN
    environment: *common-env
    ports:
      - "22222:80"

  tested:
    image: *TESTED
    environment: *common-env
    ports:
      - "33333:80"
