# This compose file is run by Jenkins, so no static ports.
version: '3'

services:

  # The image under test
  opensearch-webservice:
    image: opensearch-ws-local/opensearch-webservice${DOCKER_IMAGE_TAG}
    environment:
      # These settings modified from the fbstest.env file. I have no clue if they are "working" at this time.
      - AAA_IP_RIGHTS_BLOCK=aaa_ip_rights[dbc][ip_list] = 0.0.0.0-255.255.255.255\naaa_ip_rights[dbc][ressource][opensearch] = 500
      - AGENCY_CACHE_SETTINGS=
      - AGENCY_END_POINT=http://openagency.addi.dk/test_2.34/
      - AGENCY_FALLBACK=100200
      - AGENCY_PROFILE_FALLBACK=test
      - CACHE_SETTINGS=
      - FEDORA=http://content-service.corepo.fbstest.mcp1.dbc.dk/rest/
      - HOLDINGS_DB=http://holdings-service.fbstest.mcp1.dbc.dk/getAllAvailability?pid=%s
      - HOLDINGS_ITEMS_INDEX=corepo_20180112_1728
      - MY_DOMAIN_IP_LIST=172.16.0.0-172.20.255.255;192.168.0.0-192.168.255.255;10.255.0.0-10.255.255.255
      - OPEN_FORMAT= http://openformat-php-master.frontend-prod.svc.cloud.dbc.dk/server.php
      - OLD_OPEN_FORMAT=http://openformat.addi.dk/0.2/
      - RAW_RECORD_CONTENT_SERVICE=http://content-service.rawrepo.fbstest.mcp1.dbc.dk/RawRepoContentService
      - RAW_RECORD_REPOSITORY_NAME=raw_repo_ext_test
      - RAW_RECORD_SOLR=http://fbstest:8983/solr/fbstest-rawrepo-searcher/select
      - REPOSITORY_NAME=external_test
      - SERVICE_LOCATION=
      - SOLR=http://socl-p01:17001/solr/fbstest-corepo-searcher/select
      - VERBOSE_LEVEL=WARNING+ERROR+FATAL+STAT+TIMER+TRACE+DEBUG
      - URL_PATH=5.2
    expose:
      - 80
    ports:
      - 80

