#!/usr/bin/env bash

php -v
which dirname &> /dev/null || die "Unable to run dirname command - please install it"
export SCRIPTNAME="bootstrap"
export SCRIPT_DIR=$(dirname "$(readlink -f "$0")") || { echo "Unable to identify basedir from $0" ; exit 1; }
. "${SCRIPT_DIR}/shared.sh" || { echo "Unable to load shared file shared.sh" ; exit 1; }


set -e

check_on_path composer

SRCDIR="${PROJECT_DIR}/src"

php -v
cd "${SRCDIR}" || die "Unable to change directory to ${SRCDIR}"
composer clear-cache || die "Unable to clear the composer cache"
composer update --with-dependencies -v || die "Unable to run composer to get php dependencies"
