#!/usr/bin/env bash

which dirname &> /dev/null || die "Unable to run dirname command - please install it"
export SCRIPTNAME="build"
export SCRIPT_DIR=$(dirname "$(readlink -f "$0")") || { echo "Unable to identify basedir from $0" ; exit 1; }
. "${SCRIPT_DIR}/shared.sh" || { echo "Unable to load shared file shared.sh" ; exit 1; }

set -e

cd ${PROJECT_DIR}
check_on_path build-dockers.py
info "Building ws docker container using build-dockers.py"
MY_TAG=
if test -n "${GIT_BRANCH}" ; then
    MY_TAG="-t ${GIT_BRANCH}"
fi
# If the users sets a tag, it will override our branch tag. This is by intention.
build-dockers.py ${MY_TAG} "$@" || die "Unable to build ws docker container"
