#!/usr/bin/env bash

which dirname &> /dev/null || die "Unable to run dirname command - please install it"
export SCRIPTNAME="server"
export SCRIPT_DIR=$(dirname "$(readlink -f "$0")") || { echo "Unable to identify basedir from $0" ; exit 1; }
. "${SCRIPT_DIR}/shared.sh" || { echo "Unable to load shared file shared.sh" ; exit 1; }

set -e

DATAWELL="$1"
test -z "${DATAWELL}" && die "Usage $0 <datawell> -- where datawell is one of fbstest, boblebad or cisterne. Use fbstest if in doubt"


cd ${PROJECT_DIR}/docker
check_on_path docker docker-compose
info "Starting redis service, used for caching - depending on config"
docker-compose up --force-recreate -d redis
#info "Starting memcached-1 service, used for caching - depending on config"
#docker-compose up --force-recreate -d memcached-1
#info "Starting memcached-2 service, used for caching - depending on config"
#docker-compose up --force-recreate -d memcached-2

info "Starting ws service, based on compose file in $(pwd)"
docker-compose up --force-recreate "${DATAWELL}"

# If the users shuts down using Ctrl+C, we can shut down the redis service too
info "Shutting down docker compose containers and services"
docker-compose down

