#!/usr/bin/env bash

# TODO: No systemtest - yet.

which dirname &> /dev/null || die "Unable to run dirname command - please install it"
export SCRIPTNAME="test"
export SCRIPT_DIR=$(dirname "$(readlink -f "$0")") || { echo "Unable to identify basedir from $0" ; exit 1; }
. "${SCRIPT_DIR}/shared.sh" || { echo "Unable to load shared file shared.sh" ; exit 1; }

set -e

# Get information about the exposed port of the service from the compose file.
port=$(get_compose_service_port ${PROJECT_DIR}/docker/docker-compose.yml opensearch-webservice 80)
URL="http://localhost:${port}/5.2/"

exec ${SCRIPT_DIR}/../tests/compare_request_results.py "$@" \
  https://oss-services.dbc.dk/opensearch/5.2/ ${URL} \
  # ${SCRIPT_DIR}/../ged/
  ${SCRIPT_DIR}/../tests/requests
